### ISSUE TITLE
IEEEmadC

### ISSUE THREAD

**Issue by SangramChavan** [hzdawoud/Clinique#1]
Unable to verify the account. Can you please help!

Thank you !

**Comment by ghost** [comment]
Verification is done manually by the developers to protect users' privacy. We will manually verify you as soon as possible.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by SangramChavan** [comment]
Thank you! Please share asap. We are testing for the final results.

**Comment by SangramChavan** [comment]
Please verify the "josip" account.

**Comment by ghost** [comment]
It has been verified successfully.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
